var annotated =
[
    [ "gslc_tsCollect", "structgslc__tsCollect.html", "structgslc__tsCollect" ],
    [ "gslc_tsColor", "structgslc__tsColor.html", "structgslc__tsColor" ],
    [ "gslc_tsDriver", "structgslc__tsDriver.html", "structgslc__tsDriver" ],
    [ "gslc_tsElem", "structgslc__tsElem.html", "structgslc__tsElem" ],
    [ "gslc_tsElemRef", "structgslc__tsElemRef.html", "structgslc__tsElemRef" ],
    [ "gslc_tsEvent", "structgslc__tsEvent.html", "structgslc__tsEvent" ],
    [ "gslc_tsEventTouch", "structgslc__tsEventTouch.html", "structgslc__tsEventTouch" ],
    [ "gslc_tsFont", "structgslc__tsFont.html", "structgslc__tsFont" ],
    [ "gslc_tsGui", "structgslc__tsGui.html", "structgslc__tsGui" ],
    [ "gslc_tsImgRef", "structgslc__tsImgRef.html", "structgslc__tsImgRef" ],
    [ "gslc_tsInputMap", "structgslc__tsInputMap.html", "structgslc__tsInputMap" ],
    [ "gslc_tsPage", "structgslc__tsPage.html", "structgslc__tsPage" ],
    [ "gslc_tsPt", "structgslc__tsPt.html", "structgslc__tsPt" ],
    [ "gslc_tsRect", "structgslc__tsRect.html", "structgslc__tsRect" ],
    [ "gslc_tsXCheckbox", "structgslc__tsXCheckbox.html", "structgslc__tsXCheckbox" ],
    [ "gslc_tsXGauge", "structgslc__tsXGauge.html", "structgslc__tsXGauge" ],
    [ "gslc_tsXGraph", "structgslc__tsXGraph.html", "structgslc__tsXGraph" ],
    [ "gslc_tsXSlider", "structgslc__tsXSlider.html", "structgslc__tsXSlider" ],
    [ "gslc_tsXTextbox", "structgslc__tsXTextbox.html", "structgslc__tsXTextbox" ],
    [ "THPoint", "classTHPoint.html", "classTHPoint" ],
    [ "TouchHandler", "classTouchHandler.html", "classTouchHandler" ],
    [ "TouchHandler_XPT2046", "classTouchHandler__XPT2046.html", "classTouchHandler__XPT2046" ]
];